export const parentTimetable = {
  Mon: [
    {
      startTime: "09:00",
      endTime: "09:40",
      room: "RM 1",
      subject: "Hindi",
      teacher: "Teacher 1",
    },
    {
      startTime: "09:40",
      endTime: "10:30",
      room: "RM 4",
      subject: "Math",
      teacher: "Teacher 2",
    },
    {
      startTime: "10:30",
      endTime: "11:20",
      room: "RM 4",
      subject: "English",
      teacher: "Teacher 3",
    },
    {
      startTime: "10:44",
      endTime: "10:50",
      room: "RM TBD",
      subject: "Telugu",
      teacher: "Teacher 4",
    },
  ],
  Tue: [
    {
      startTime: "09:00",
      endTime: "09:40",
      room: "RM TBD",
      subject: "English",
      teacher: "Teacher 5",
    },
    {
      startTime: "09:40",
      endTime: "10:30",
      room: "RM TBD",
      subject: "Telugu",
      teacher: "Teacher 6",
    },
    { startTime: "10:30", endTime: "11:20" },
    {
      startTime: "10:44",
      endTime: "10:50",
      room: "RM TBD",
      subject: "Hindi",
      teacher: "Teacher 7",
    },
  ],
  Wed: [
    {
      startTime: "09:00",
      endTime: "09:40",
      room: "RM TBD",
      subject: "Telugu",
      teacher: "Teacher 8",
    },
    {
      startTime: "09:40",
      endTime: "10:30",
      room: "RM TBD",
      subject: "Telugu",
      teacher: "Teacher 9",
    },
    { startTime: "10:30", endTime: "11:20" },
    {
      startTime: "10:44",
      endTime: "10:50",
      room: "RM TBD",
      subject: "Telugu",
      teacher: "Teacher 10",
    },
  ],
  Thu: [
    {
      startTime: "09:00",
      endTime: "09:40",
      room: "RM 102",
      subject: "Science",
      teacher: "Teacher 11",
    },
    {
      startTime: "09:40",
      endTime: "10:30",
      room: "RM TBD",
      subject: "English",
      teacher: "Teacher 12",
    },
    { startTime: "10:30", endTime: "11:20" },
    {
      startTime: "10:44",
      endTime: "10:50",
      room: "RM TBD",
      subject: "Telugu",
      teacher: "Teacher 13",
    },
  ],
  Fri: [
    {
      startTime: "09:00",
      endTime: "09:40",
      room: "RM 1",
      subject: "Math",
      teacher: "Teacher 14",
    },
    {
      startTime: "09:40",
      endTime: "10:30",
      room: "RM 4",
      subject: "English",
      teacher: "Teacher 15",
    },
    { startTime: "10:30", endTime: "11:20" },
    {
      startTime: "10:44",
      endTime: "10:50",
      room: "RM TBD",
      subject: "Telugu",
      teacher: "Teacher 16",
    },
  ],
  Sat: [
    {
      startTime: "09:00",
      endTime: "09:40",
      room: "RM 1",
      subject: "Science",
      teacher: "Teacher 17",
    },
    {
      startTime: "09:40",
      endTime: "10:30",
      room: "RM TBD",
      subject: "English",
      teacher: "Teacher 18",
    },
    { startTime: "10:30", endTime: "11:20" },
    {
      startTime: "10:44",
      endTime: "10:50",
      room: "RM TBD",
      subject: "Telugu",
      teacher: "Teacher 19",
    },
  ],
};
